spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hgm_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  type-aliases-package: top.serms.pojo # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
